# Stage 1: Build FastAPI application
FROM python:3.9 AS builder

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Set the working directory in the container
WORKDIR /app

# Copy only the requirements file to the container
COPY requirements.txt /app/

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the entire FastAPI application to the container
COPY . /app

# Expose the port that FastAPI runs on
EXPOSE 8000
